version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-super_secret_key_that_should_be_env_var}
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Additional services would be added here as needed
  # For example:
  # - PostgreSQL database
  # - Redis for caching
  # - Frontend service
  # - Elasticsearch for search
  # - etc.

networks:
  default:
    driver: bridge
